name: Deploy User Backend to Local Windows Docker

on:
  push:
    branches: [ "prod" ]

jobs:
  deploy:
    name: Deploy User API on Local Machine
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create .env file
      run: |
        "DB_URL=${{ secrets.DB_URL }}" | Out-File -FilePath .env -Encoding utf8
        "DB_USERNAME=${{ secrets.DB_USERNAME }}" | Out-File -FilePath .env -Append -Encoding utf8
        "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" | Out-File -FilePath .env -Append -Encoding utf8
      shell: pwsh

    - name: Docker Compose Down
      run: docker-compose down --remove-orphans
      continue-on-error: true
      shell: pwsh

    - name: Docker Compose Up
      run: docker-compose up -d --build
      shell: pwsh
