name: Deploy User Backend to Local Windows Docker

on:
  push:
    branches: [ "prod" ]

jobs:
  deploy:
    name: Deploy User API on Local Machine
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create .env file
      run: |
        echo "DB_URL=${{ secrets.DB_URL }}" > .env
        echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
      shell: bash

    - name: Docker Compose Down
      # Stop and remove containers, networks
      run: docker-compose down --remove-orphans
      continue-on-error: true

    - name: Docker Compose Up
      # Build and start in background
      run: docker-compose up -d --build
